"""
Static, deterministic source-field contract catalog for DQ-001A.

Names concrete SQLite columns for the core market/broker/observation/label
tables, so this lives in infrastructure. Application receives the resulting
SourceFieldContract objects through injection and never sees column names
directly.

Layer: Infrastructure
"""

from __future__ import annotations

from src.application.use_case.audit_source_field_contracts_use_case import (
    SourceFieldContract,
    SourceFieldContractCatalog,
)

_AUDITED_TABLES: tuple[str, ...] = (
    "candles",
    "broker_summaries",
    "broker_daily_flow",
    "candidate_observations",
    "signal_forward_labels",
)

_CANDLES_FIELDS: tuple[SourceFieldContract, ...] = (
    SourceFieldContract(
        field="ticker",
        required=True,
        semantic_name="IDX ticker symbol",
        source_owner="candle provider",
        unit="text",
        sign_convention=None,
        aggregation="none",
        grain="one row per ticker/session/source",
        temporal_meaning="market session date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="date",
        required=True,
        semantic_name="Trading session date",
        source_owner="candle provider",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="none",
        grain="one row per ticker/session/source",
        temporal_meaning="IDX trading session date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    *(
        SourceFieldContract(
            field=name,
            required=True,
            semantic_name=f"{name.capitalize()} price",
            source_owner="candle provider",
            unit="IDR price",
            sign_convention="positive price",
            aggregation="daily OHLC",
            grain="one row per ticker/session/source",
            temporal_meaning="session price at IDX trading date",
            null_semantics="unavailable if null",
            point_in_time_support="HISTORICAL",
            null_policy="fail",
        )
        for name in ("open", "high", "low", "close")
    ),
    SourceFieldContract(
        field="volume",
        required=True,
        semantic_name="Traded volume",
        source_owner="candle provider",
        unit="source-specific volume; must be interpreted with volume_unit",
        sign_convention="non-negative",
        aggregation="daily traded volume",
        grain="one row per ticker/session/source",
        temporal_meaning="session traded volume",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="source",
        required=True,
        semantic_name="Candle data provider id",
        source_owner="candle provider",
        unit="provider id",
        sign_convention=None,
        aggregation="none",
        grain="one row per ticker/session/source",
        temporal_meaning="none",
        null_semantics="unknown source is invalid for canonical audit",
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
        invalid_values=frozenset({"unknown"}),
        invalid_value_policy="fail",
    ),
    SourceFieldContract(
        field="volume_unit",
        required=True,
        semantic_name="Unit of the volume field",
        source_owner="candle provider",
        unit="shares/lots/unknown",
        sign_convention=None,
        aggregation="none",
        grain="one row per ticker/session/source",
        temporal_meaning="none",
        null_semantics="unknown unit makes volume unusable for cross-source math",
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
        invalid_values=frozenset({"unknown"}),
        invalid_value_policy="fail",
    ),
    SourceFieldContract(
        field="price_adjustment_policy",
        required=True,
        semantic_name="Adjustment policy applied to OHLC",
        source_owner="candle provider",
        unit="raw/adjusted/unknown",
        sign_convention=None,
        aggregation="none",
        grain="one row per ticker/session/source",
        temporal_meaning="none",
        null_semantics="unknown policy makes price comparisons across dates unsafe",
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
        invalid_values=frozenset({"unknown"}),
        invalid_value_policy="fail",
    ),
)

_BROKER_SUMMARIES_FIELDS: tuple[SourceFieldContract, ...] = (
    SourceFieldContract(
        field="ticker",
        required=True,
        semantic_name="IDX ticker symbol",
        source_owner="IDX/Stockbit broker summary provider",
        unit="text",
        sign_convention=None,
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="market session date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="date",
        required=True,
        semantic_name="Session date",
        source_owner="IDX/Stockbit broker summary provider",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="IDX trading session date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="source",
        required=True,
        semantic_name="Broker summary provider id",
        source_owner="IDX/Stockbit broker summary provider",
        unit="provider id",
        sign_convention=None,
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="foreign_buy_value",
        required=True,
        semantic_name="Foreign buy value",
        source_owner="IDX/Stockbit broker summary provider",
        unit="IDR",
        sign_convention="non-negative",
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="session value",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="foreign_sell_value",
        required=True,
        semantic_name="Foreign sell value",
        source_owner="IDX/Stockbit broker summary provider",
        unit="IDR",
        sign_convention="non-negative",
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="session value",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="foreign_net_value",
        required=True,
        semantic_name="Foreign net value (derived, not a stored column)",
        source_owner="IDX/Stockbit broker summary provider",
        unit="IDR",
        sign_convention="foreign_net_value = foreign_buy_value - foreign_sell_value",
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="session value",
        null_semantics="derived from foreign_buy_value/foreign_sell_value; null if either is null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="foreign_buy_lot",
        required=True,
        semantic_name="Foreign buy lots",
        source_owner="IDX/Stockbit broker summary provider",
        unit="lot",
        sign_convention="non-negative",
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="session value",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="foreign_sell_lot",
        required=True,
        semantic_name="Foreign sell lots",
        source_owner="IDX/Stockbit broker summary provider",
        unit="lot",
        sign_convention="non-negative",
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="session value",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="total_value",
        required=True,
        semantic_name="Total traded value",
        source_owner="IDX/Stockbit broker summary provider",
        unit="IDR",
        sign_convention="non-negative",
        aggregation="daily ticker-level broker summary",
        grain="one row per ticker/date/source",
        temporal_meaning="session value",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
)

_BROKER_DAILY_FLOW_FIELDS: tuple[SourceFieldContract, ...] = (
    SourceFieldContract(
        field="ticker",
        required=True,
        semantic_name="IDX ticker symbol",
        source_owner="Stockbit tracked broker activity",
        unit="text",
        sign_convention=None,
        aggregation="tracked broker subset, not full market",
        grain="one row per ticker/date/tracked broker/source",
        temporal_meaning="market session date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="date",
        required=True,
        semantic_name="Session date",
        source_owner="Stockbit tracked broker activity",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="tracked broker subset, not full market",
        grain="one row per ticker/date/tracked broker/source",
        temporal_meaning="IDX trading session date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="broker_code",
        required=True,
        semantic_name="Tracked broker code",
        source_owner="Stockbit tracked broker activity",
        unit="broker code",
        sign_convention=None,
        aggregation="tracked broker subset, not full market",
        grain="one row per ticker/date/tracked broker/source",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="source",
        required=True,
        semantic_name="Broker flow provider id",
        source_owner="Stockbit tracked broker activity",
        unit="provider id",
        sign_convention=None,
        aggregation="tracked broker subset, not full market",
        grain="one row per ticker/date/tracked broker/source",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    *(
        SourceFieldContract(
            field=name,
            required=True,
            semantic_name=f"Tracked broker {name.replace('_', ' ')}",
            source_owner="Stockbit tracked broker activity",
            unit="IDR" if "value" in name else "lot",
            sign_convention=(
                "net_value = buy_value - sell_value"
                if name == "net_value"
                else "net_lot = buy_lot - sell_lot" if name == "net_lot" else "non-negative"
            ),
            aggregation="tracked broker subset, not full market",
            grain="one row per ticker/date/tracked broker/source",
            temporal_meaning="session value",
            null_semantics="unavailable if null",
            point_in_time_support="HISTORICAL",
            null_policy="warn",
        )
        for name in ("buy_value", "sell_value", "net_value", "buy_lot", "sell_lot", "net_lot")
    ),
)

_CANDIDATE_OBSERVATIONS_FIELDS: tuple[SourceFieldContract, ...] = (
    SourceFieldContract(
        field="ticker",
        required=True,
        semantic_name="IDX ticker symbol",
        source_owner="local observation recorder",
        unit="text",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="observed ticker",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="snapshot_date",
        required=True,
        semantic_name="Nominal observation date",
        source_owner="local observation recorder",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="nominal observation date",
        null_semantics="unavailable if null",
        point_in_time_support="UNVERIFIED",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="captured_at",
        required=True,
        semantic_name="Write timestamp",
        source_owner="local observation recorder",
        unit="ISO timestamp",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="write timestamp, not identity",
        null_semantics="unavailable if null",
        point_in_time_support="UNVERIFIED",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="schema_version",
        required=True,
        semantic_name="Observation payload schema version",
        source_owner="local observation recorder",
        unit="integer",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="UNVERIFIED",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="payload_json",
        required=True,
        semantic_name="Serialized observation payload",
        source_owner="local observation recorder",
        unit="json",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="UNVERIFIED",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="workflow",
        required=True,
        semantic_name="Producing workflow identity component",
        source_owner="local observation recorder",
        unit="text",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="window_sessions",
        required=True,
        semantic_name="Observation window size identity component",
        source_owner="local observation recorder",
        unit="sessions (integer)",
        sign_convention="non-negative",
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="data_as_of_date",
        required=True,
        semantic_name="Source data currency date",
        source_owner="local observation recorder",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="source data currency date",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="config_hash",
        required=True,
        semantic_name="Resolved config identity hash",
        source_owner="local observation recorder",
        unit="hex digest",
        sign_convention=None,
        aggregation="none",
        grain="one observation per canonical workflow/window/data_as_of/config identity",
        temporal_meaning="none",
        null_semantics=(
            "empty string ('') means legacy/non-canonical identity, not a valid "
            "canonical identity — flagged separately, not a null-count failure"
        ),
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
)

_SIGNAL_FORWARD_LABELS_FIELDS: tuple[SourceFieldContract, ...] = (
    SourceFieldContract(
        field="ticker",
        required=True,
        semantic_name="IDX ticker symbol",
        source_owner="local forward-label generator",
        unit="text",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="labeled ticker",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="signal_date",
        required=True,
        semantic_name="Observation signal date",
        source_owner="local forward-label generator",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="label generated only after forward window is complete",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="horizon",
        required=True,
        semantic_name="Forward label horizon identity",
        source_owner="local forward-label generator",
        unit="text",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="observation_captured_at",
        required=True,
        semantic_name="Bound observation identity timestamp",
        source_owner="local forward-label generator",
        unit="ISO timestamp",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="binds label to exact observation identity",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="entry_reference_price",
        required=True,
        semantic_name="Executable entry reference price",
        source_owner="local forward-label generator",
        unit="IDR price (text)",
        sign_convention="positive price",
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="entry reference for forward return calculation",
        null_semantics="unavailable if null; label may be UNTRADEABLE/UNAVAILABLE",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="label_window_start",
        required=True,
        semantic_name="Forward label window start date",
        source_owner="local forward-label generator",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="first session of the forward outcome window",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="label_window_end",
        required=True,
        semantic_name="Forward label window end date",
        source_owner="local forward-label generator",
        unit="YYYY-MM-DD",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="last session of the forward outcome window",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="warn",
    ),
    SourceFieldContract(
        field="close_return",
        required=True,
        semantic_name="Close-to-close forward return",
        source_owner="local forward-label generator",
        unit="ratio",
        sign_convention="positive is favorable",
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="realized over the forward label window",
        null_semantics=(
            "null is valid only when outcome_label is UNAVAILABLE; complete labels "
            "must have this populated (checked via table-level rule, not blanket null count)"
        ),
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
    ),
    SourceFieldContract(
        field="max_forward_return",
        required=True,
        semantic_name="Maximum favorable forward return",
        source_owner="local forward-label generator",
        unit="ratio",
        sign_convention="positive is favorable",
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="realized over the forward label window",
        null_semantics="null is valid only when outcome_label is UNAVAILABLE",
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
    ),
    SourceFieldContract(
        field="max_adverse_excursion",
        required=True,
        semantic_name="Maximum adverse forward excursion",
        source_owner="local forward-label generator",
        unit="ratio",
        sign_convention="negative is adverse",
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="realized over the forward label window",
        null_semantics="null is valid only when outcome_label is UNAVAILABLE",
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
    ),
    SourceFieldContract(
        field="outcome_label",
        required=True,
        semantic_name="Label completeness/outcome classification",
        source_owner="local forward-label generator",
        unit="text enum",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="determined after forward window completeness check",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="unavailable_reason",
        required=True,
        semantic_name="Reason the outcome is unavailable",
        source_owner="local forward-label generator",
        unit="text",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="none",
        null_semantics=(
            "null is valid when outcome_label != UNAVAILABLE; required when "
            "outcome_label == UNAVAILABLE (checked via table-level rule)"
        ),
        point_in_time_support="HISTORICAL",
        null_policy="ignore",
    ),
    SourceFieldContract(
        field="fingerprint_json",
        required=True,
        semantic_name="Serialized label fingerprint",
        source_owner="local forward-label generator",
        unit="json",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
    SourceFieldContract(
        field="schema_version",
        required=True,
        semantic_name="Label payload schema version",
        source_owner="local forward-label generator",
        unit="integer",
        sign_convention=None,
        aggregation="none",
        grain="one label per ticker/signal_date/horizon/observation_captured_at",
        temporal_meaning="none",
        null_semantics="unavailable if null",
        point_in_time_support="HISTORICAL",
        null_policy="fail",
    ),
)

_CATALOG: dict[str, tuple[SourceFieldContract, ...]] = {
    "candles": _CANDLES_FIELDS,
    "broker_summaries": _BROKER_SUMMARIES_FIELDS,
    "broker_daily_flow": _BROKER_DAILY_FLOW_FIELDS,
    "candidate_observations": _CANDIDATE_OBSERVATIONS_FIELDS,
    "signal_forward_labels": _SIGNAL_FORWARD_LABELS_FIELDS,
}

# Reader-only hints: not part of the application-visible SourceFieldContract.
# "date" and "identity_text"/"enum_text" drive distinct-count/min-max queries;
# "numeric" is for columns safely MIN/MAX-able directly (INTEGER/REAL);
# "numeric_text" is for IDR/price values stored as TEXT needing CAST; "none"
# skips stats entirely (large json blobs, write timestamps not worth ranging).
FIELD_STATS_MODE: dict[tuple[str, str], str] = {
    ("candles", "ticker"): "identity_text",
    ("candles", "date"): "date",
    ("candles", "open"): "numeric_text",
    ("candles", "high"): "numeric_text",
    ("candles", "low"): "numeric_text",
    ("candles", "close"): "numeric_text",
    ("candles", "volume"): "numeric",
    ("candles", "source"): "enum_text",
    ("candles", "volume_unit"): "enum_text",
    ("candles", "price_adjustment_policy"): "enum_text",
    ("broker_summaries", "ticker"): "identity_text",
    ("broker_summaries", "date"): "date",
    ("broker_summaries", "source"): "enum_text",
    ("broker_summaries", "foreign_buy_value"): "numeric_text",
    ("broker_summaries", "foreign_sell_value"): "numeric_text",
    ("broker_summaries", "foreign_buy_lot"): "numeric",
    ("broker_summaries", "foreign_sell_lot"): "numeric",
    ("broker_summaries", "total_value"): "numeric_text",
    ("broker_daily_flow", "ticker"): "identity_text",
    ("broker_daily_flow", "date"): "date",
    ("broker_daily_flow", "broker_code"): "enum_text",
    ("broker_daily_flow", "source"): "enum_text",
    ("broker_daily_flow", "buy_value"): "numeric_text",
    ("broker_daily_flow", "sell_value"): "numeric_text",
    ("broker_daily_flow", "net_value"): "numeric_text",
    ("broker_daily_flow", "buy_lot"): "numeric",
    ("broker_daily_flow", "sell_lot"): "numeric",
    ("broker_daily_flow", "net_lot"): "numeric",
    ("candidate_observations", "ticker"): "identity_text",
    ("candidate_observations", "snapshot_date"): "date",
    ("candidate_observations", "captured_at"): "date",
    ("candidate_observations", "schema_version"): "numeric",
    ("candidate_observations", "payload_json"): "none",
    ("candidate_observations", "workflow"): "enum_text",
    ("candidate_observations", "window_sessions"): "numeric",
    ("candidate_observations", "data_as_of_date"): "date",
    ("candidate_observations", "config_hash"): "enum_text",
    ("signal_forward_labels", "ticker"): "identity_text",
    ("signal_forward_labels", "signal_date"): "date",
    ("signal_forward_labels", "horizon"): "enum_text",
    ("signal_forward_labels", "observation_captured_at"): "date",
    ("signal_forward_labels", "entry_reference_price"): "numeric_text",
    ("signal_forward_labels", "label_window_start"): "date",
    ("signal_forward_labels", "label_window_end"): "date",
    ("signal_forward_labels", "close_return"): "numeric",
    ("signal_forward_labels", "max_forward_return"): "numeric",
    ("signal_forward_labels", "max_adverse_excursion"): "numeric",
    ("signal_forward_labels", "outcome_label"): "enum_text",
    ("signal_forward_labels", "unavailable_reason"): "enum_text",
    ("signal_forward_labels", "fingerprint_json"): "none",
    ("signal_forward_labels", "schema_version"): "numeric",
}

# Fields that are not stored columns but computed from other stored columns.
# The reader treats these specially: existence/nulls derive from the
# component columns rather than a literal column lookup.
DERIVED_FIELDS: dict[tuple[str, str], tuple[str, ...]] = {
    ("broker_summaries", "foreign_net_value"): ("foreign_buy_value", "foreign_sell_value"),
}


class StaticSourceFieldContractCatalog(SourceFieldContractCatalog):
    """Static DQ-001A contract catalog for core tables."""

    def tables(self) -> tuple[str, ...]:
        return _AUDITED_TABLES

    def contracts_for_table(self, table: str) -> tuple[SourceFieldContract, ...]:
        return _CATALOG.get(table, ())
