from src.application.dto.swing_backtest_attribution import TuningTarget

DEFAULT_TUNING_TARGETS: tuple[TuningTarget, ...] = (
    TuningTarget(
        dimension="trade_setup_action",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.trade_setup_action",
        meaning="Final TradeSetup action observed on executed portfolio trades.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.classification",
            "config/signal_engine.yaml:signal_engine.classification.strong_min_score",
            "config/signal_engine.yaml:signal_engine.classification.moderate_min_score",
            "config/signal_engine.yaml:signal_engine.evidence_groups",
            "config/risk_engine.yaml:risk_engine.gates",
        ),
        allowed_use="Tune final signal/risk thresholds only from executed-trade outcomes.",
    ),
    TuningTarget(
        dimension="signal_strength",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.signal_strength",
        meaning="SignalAssessment strength bucket on executed portfolio trades.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.classification.strong_min_score",
            "config/signal_engine.yaml:signal_engine.classification.moderate_min_score",
            "config/signal_engine.yaml:signal_engine.classification.enter_min_confidence",
            "config/signal_engine.yaml:signal_engine.classification.watch_min_confidence",
        ),
        allowed_use=(
            "Tune signal classification score thresholds and confidence gating "
            "from completed trade outcomes."
        ),
    ),
    TuningTarget(
        dimension="signal_score_bucket",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.signal_score",
        meaning="Bucketed SignalEngine total score on executed portfolio trades.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.classification",
            "config/signal_engine.yaml:signal_engine.classification.strong_min_score",
            "config/signal_engine.yaml:signal_engine.classification.moderate_min_score",
            "config/swing_backtest.yaml:swing_backtest.attribution.score_buckets",
            "config/swing_backtest.yaml:swing_backtest.attribution.score_buckets.high_min_score",
            "config/swing_backtest.yaml:swing_backtest.attribution.score_buckets.mid_min_score",
        ),
        allowed_use="Tune score thresholds; attribution buckets are reporting-only.",
    ),
    TuningTarget(
        dimension="signal_factor_bucket",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.signal_breakdown",
        meaning="Bucketed SignalEngine evidence group scores on executed portfolio trades.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.evidence_groups",
            "config/signal_engine.yaml:signal_engine.evidence_groups.setup_quality.weight",
            "config/signal_engine.yaml:signal_engine.evidence_groups.flow_confirmation.weight",
            "config/signal_engine.yaml:signal_engine.flags",
            "config/signal_engine.yaml:signal_engine.flags.valuation_stretched.score_penalty",
            "config/signal_engine.yaml:signal_engine.flags.analyst_bearish.score_penalty",
            "config/signal_engine.yaml:signal_engine.flags.insider_selling.score_penalty",
            "config/signal_engine.yaml:signal_engine.classification.enter_min_confidence",
            "config/signal_engine.yaml:signal_engine.classification.watch_min_confidence",
            "config/signal_engine.yaml:signal_engine.scoring.bandar",
        ),
        allowed_use=(
            "Tune evidence group weights, flag penalty thresholds, and "
            "confidence gating."
        ),
    ),
    TuningTarget(
        dimension="risk_status",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.risk_status",
        meaning="RiskEngine OPEN/BLOCKED status recorded on executed portfolio trades.",
        config_family="risk",
        yaml_paths=(
            "config/risk_engine.yaml:risk_engine.gates",
            "config/risk_engine.yaml:risk_engine.gates.fundamental.piotroski_min",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.market_cap_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.median_tx_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.free_float.min_free_float_pct",
        ),
        allowed_use="Tune risk gate policy only with candidate stats as a bias check.",
        warning="Completed trades can underrepresent blocked/rejected candidates.",
    ),
    TuningTarget(
        dimension="risk_gate",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.risk_gate",
        meaning="Risk gate label recorded on executed portfolio trades.",
        config_family="risk",
        yaml_paths=(
            "config/risk_engine.yaml:risk_engine.gates",
            "config/risk_engine.yaml:risk_engine.gates.fundamental.piotroski_min",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.market_cap_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.median_tx_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.free_float.min_free_float_pct",
        ),
        allowed_use="Tune gate thresholds only with candidate stats as a bias check.",
        warning="Completed trades can underrepresent blocked/rejected candidates.",
    ),
    TuningTarget(
        dimension="setup_gate",
        source_scope="completed_trades_and_screened_candidates",
        source_field="SetupGate.label + SetupGate.passed",
        meaning="Pass/fail state for named swing setup gates.",
        config_family="setup",
        yaml_paths=("config/swing_setups.yaml:setups.*.gates",),
        allowed_use="Tune setup gates using candidate_group_stats first; trades are confirmation.",
    ),
    TuningTarget(
        dimension="regime",
        source_scope="completed_trades",
        source_field="SwingBacktestTrade.regime",
        meaning="MarketContext regime on executed portfolio trades.",
        config_family="market_context",
        yaml_paths=(
            "config/market_context_engine.yaml:market_context_engine",
            "config/market_context_engine.yaml:market_context_engine.regime_thresholds.risk_on_min_score",
            "config/market_context_engine.yaml:market_context_engine.regime_thresholds.risk_off_max_score",
            "config/market_context_engine.yaml:market_context_engine.regime_thresholds.volatile_vix_override",
            "config/market_context_engine.yaml:market_context_engine.regime_effects.RISK_OFF.signal_multiplier",
            "config/market_context_engine.yaml:market_context_engine.regime_effects.VOLATILE.signal_multiplier",
            "config/signal_engine.yaml:signal_engine.decision_policy",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.enter_threshold",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.watch_threshold",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.min_coverage",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.min_conviction",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.regime_size_multiplier",
            "config/swing_targets.yaml:setup_targets",
            "config/swing_targets.yaml:setup_targets.risk_on.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.risk_on.stop_loss_pct",
            "config/swing_targets.yaml:setup_targets.neutral.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.neutral.stop_loss_pct",
            "config/swing_targets.yaml:setup_targets.risk_off.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.risk_off.stop_loss_pct",
            "config/swing_targets.yaml:setup_targets.volatile.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.volatile.stop_loss_pct",
        ),
        allowed_use=(
            "Tune regime detection thresholds (market_context_engine.yaml) and "
            "regime-adaptive exits (swing_targets.yaml) from executed trades. "
            "Tune explicit decision_policy regime caps/multipliers instead of "
            "legacy score conditioning. "
            "Do NOT tune signal_engine.regime_conditioning \u2014 frozen legacy layer (TD-1)."
        ),
    ),
    TuningTarget(
        dimension="candidate_setup_match",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.setup_match",
        meaning="Setup fit result for every screened candidate with forward data.",
        config_family="setup",
        yaml_paths=(
            "config/swing_setups.yaml:setups.*.gates",
            "config/swing_setups.yaml:setups.*.partial_max_failed_gates",
        ),
        allowed_use="Primary evidence for setup gate tuning; not an executed trade result.",
    ),
    TuningTarget(
        dimension="candidate_signal_strength",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.signal_strength",
        meaning="Signal strength on every screened candidate with forward data.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.classification",
            "config/signal_engine.yaml:signal_engine.classification.strong_min_score",
            "config/signal_engine.yaml:signal_engine.classification.moderate_min_score",
            "config/signal_engine.yaml:signal_engine.classification.enter_min_confidence",
            "config/signal_engine.yaml:signal_engine.classification.watch_min_confidence",
        ),
        allowed_use=(
            "Bias check for signal score thresholds and confidence gating "
            "before validating on completed trades."
        ),
    ),
    TuningTarget(
        dimension="candidate_signal_score_bucket",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.signal_score",
        meaning="Bucketed SignalEngine score on every screened candidate with forward data.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.classification",
            "config/signal_engine.yaml:signal_engine.classification.strong_min_score",
            "config/signal_engine.yaml:signal_engine.classification.moderate_min_score",
            "config/swing_backtest.yaml:swing_backtest.attribution.score_buckets",
            "config/swing_backtest.yaml:swing_backtest.attribution.score_buckets.high_min_score",
            "config/swing_backtest.yaml:swing_backtest.attribution.score_buckets.mid_min_score",
        ),
        allowed_use="Bias check for signal score thresholds; buckets are reporting-only.",
    ),
    TuningTarget(
        dimension="candidate_signal_factor_bucket",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.signal_breakdown",
        meaning="Bucketed evidence group scores on every screened candidate with forward data.",
        config_family="signal",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine.evidence_groups",
            "config/signal_engine.yaml:signal_engine.evidence_groups.setup_quality.weight",
            "config/signal_engine.yaml:signal_engine.evidence_groups.flow_confirmation.weight",
            "config/signal_engine.yaml:signal_engine.flags",
            "config/signal_engine.yaml:signal_engine.flags.valuation_stretched.score_penalty",
            "config/signal_engine.yaml:signal_engine.flags.analyst_bearish.score_penalty",
            "config/signal_engine.yaml:signal_engine.flags.insider_selling.score_penalty",
            "config/signal_engine.yaml:signal_engine.classification.enter_min_confidence",
            "config/signal_engine.yaml:signal_engine.classification.watch_min_confidence",
            "config/signal_engine.yaml:signal_engine.scoring.bandar",
        ),
        allowed_use=(
            "Bias check for evidence group tuning and confidence gating before "
            "completed-trade validation."
        ),
    ),
    TuningTarget(
        dimension="candidate_risk_status",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.risk_status",
        meaning="RiskEngine OPEN/BLOCKED status on every screened candidate with forward data.",
        config_family="risk",
        yaml_paths=(
            "config/risk_engine.yaml:risk_engine.gates",
            "config/risk_engine.yaml:risk_engine.gates.fundamental.piotroski_min",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.market_cap_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.median_tx_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.free_float.min_free_float_pct",
        ),
        allowed_use="Primary evidence for risk gate tuning; not an executed trade result.",
    ),
    TuningTarget(
        dimension="candidate_risk_gate",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.risk_gate",
        meaning="Risk gate label on every screened candidate with forward data.",
        config_family="risk",
        yaml_paths=(
            "config/risk_engine.yaml:risk_engine.gates",
            "config/risk_engine.yaml:risk_engine.gates.fundamental.piotroski_min",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.market_cap_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.median_tx_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.free_float.min_free_float_pct",
        ),
        allowed_use="Primary evidence for risk gate threshold tuning.",
    ),
    TuningTarget(
        dimension="candidate_trade_setup_action",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.trade_setup_action",
        meaning="TradeSetup action on every screened candidate with forward data.",
        config_family="signal_and_risk",
        yaml_paths=(
            "config/signal_engine.yaml:signal_engine",
            "config/signal_engine.yaml:signal_engine.classification.strong_min_score",
            "config/signal_engine.yaml:signal_engine.classification.moderate_min_score",
            "config/risk_engine.yaml:risk_engine",
            "config/risk_engine.yaml:risk_engine.gates.fundamental.piotroski_min",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.market_cap_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.liquidity.median_tx_floor_idr",
            "config/risk_engine.yaml:risk_engine.gates.free_float.min_free_float_pct",
        ),
        allowed_use="Bias check for final action composition; not portfolio execution.",
    ),
    TuningTarget(
        dimension="candidate_regime",
        source_scope="screened_candidates",
        source_field="SwingBacktestCandidateObservation.regime",
        meaning="MarketContext regime on every screened candidate with forward data.",
        config_family="market_context",
        yaml_paths=(
            "config/market_context_engine.yaml:market_context_engine",
            "config/market_context_engine.yaml:market_context_engine.regime_thresholds.risk_on_min_score",
            "config/market_context_engine.yaml:market_context_engine.regime_thresholds.risk_off_max_score",
            "config/market_context_engine.yaml:market_context_engine.regime_thresholds.volatile_vix_override",
            "config/market_context_engine.yaml:market_context_engine.regime_effects.RISK_OFF.signal_multiplier",
            "config/market_context_engine.yaml:market_context_engine.regime_effects.VOLATILE.signal_multiplier",
            "config/signal_engine.yaml:signal_engine.decision_policy",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.enter_threshold",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.watch_threshold",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.min_coverage",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.min_conviction",
            "config/signal_engine.yaml:signal_engine.decision_policy.regime_policy.*.regime_size_multiplier",
            "config/swing_targets.yaml:setup_targets",
            "config/swing_targets.yaml:setup_targets.risk_on.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.risk_on.stop_loss_pct",
            "config/swing_targets.yaml:setup_targets.neutral.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.neutral.stop_loss_pct",
            "config/swing_targets.yaml:setup_targets.risk_off.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.risk_off.stop_loss_pct",
            "config/swing_targets.yaml:setup_targets.volatile.take_profit_pct",
            "config/swing_targets.yaml:setup_targets.volatile.stop_loss_pct",
        ),
        allowed_use="Bias check for market context tuning before completed-trade validation.",
    ),
)
