"""
SKILLS_INDEX.md generator.

Scans the project for SKILL.md files and generates a catalog index.

Layer: Infrastructure
"""

import re
from pathlib import Path


class SkillIndexWriter:
    """Generates SKILLS_INDEX.md by scanning for SKILL.md files."""

    _HEADING_PATTERN = re.compile(r"^#\s+(.+)$", re.MULTILINE)
    _TYPE_PATTERN = re.compile(r"\*\*Type:\*\*\s*(\w+)", re.MULTILINE)
    _TAGS_PATTERN = re.compile(r"## Tags\n\n(.+)", re.MULTILINE)

    def generate(self, project_root: Path) -> str:
        """Scan project for SKILL.md files and produce index markdown.

        Args:
            project_root: Root directory of the project.

        Returns:
            Rendered SKILLS_INDEX.md content.
        """
        entries = self._scan_skill_files(project_root)

        parts: list[str] = []
        parts.append("# Skills Index\n")
        parts.append(
            "Catalog of all documented artifacts in this project.\n"
        )

        # Group by type
        strategies = [e for e in entries if e["type"] == "strategy"]
        indicators = [e for e in entries if e["type"] == "indicator"]
        formulas = [e for e in entries if e["type"] == "formula"]
        other = [
            e
            for e in entries
            if e["type"] not in ("strategy", "indicator", "formula")
        ]

        if strategies:
            parts.append("## Strategies\n")
            parts.append(self._render_table(strategies, project_root))

        if indicators:
            parts.append("## Indicators\n")
            parts.append(self._render_table(indicators, project_root))

        if formulas:
            parts.append("## Formulas\n")
            parts.append(self._render_table(formulas, project_root))

        if other:
            parts.append("## Other\n")
            parts.append(self._render_table(other, project_root))

        parts.append(
            "---\n*Auto-generated by `saham skill index`. Do not edit directly.*\n"
        )

        return "\n".join(parts)

    def write(self, project_root: Path) -> Path:
        """Write SKILLS_INDEX.md to the project root.

        Args:
            project_root: Root directory of the project.

        Returns:
            Path to the written SKILLS_INDEX.md.
        """
        content = self.generate(project_root)
        output_path = project_root / "SKILLS_INDEX.md"
        output_path.write_text(content, encoding="utf-8")
        return output_path

    def _scan_skill_files(self, project_root: Path) -> list[dict]:
        """Scan for all SKILL.md files under project root."""
        entries: list[dict] = []

        for skill_path in sorted(project_root.rglob("*SKILL.md")):
            # Skip node_modules, .git, etc.
            parts_str = str(skill_path)
            if "node_modules" in parts_str or "/.git/" in parts_str:
                continue

            try:
                content = skill_path.read_text(encoding="utf-8")
                entry = self._parse_skill_md(content, skill_path)
                entries.append(entry)
            except OSError:
                continue

        return entries

    def _parse_skill_md(self, content: str, path: Path) -> dict:
        """Extract metadata from a SKILL.md file."""
        # Extract name from first heading
        name_match = self._HEADING_PATTERN.search(content)
        name = name_match.group(1) if name_match else path.stem

        # Extract type
        type_match = self._TYPE_PATTERN.search(content)
        artifact_type = type_match.group(1).lower() if type_match else "unknown"

        # Extract description (first paragraph after ## Description)
        description = ""
        desc_section = content.split("## Description")
        if len(desc_section) > 1:
            desc_body = desc_section[1].split("##")[0].strip()
            # Take first line/paragraph
            first_line = desc_body.split("\n")[0].strip()
            if first_line and not first_line.startswith("<!--"):
                description = first_line

        # Extract tags
        tags = ""
        tags_match = self._TAGS_PATTERN.search(content)
        if tags_match:
            tags = tags_match.group(1).strip()

        return {
            "name": name,
            "type": artifact_type,
            "description": description,
            "tags": tags,
            "path": path,
        }

    def _render_table(self, entries: list[dict], project_root: Path) -> str:
        """Render a markdown table for a group of entries."""
        lines: list[str] = []
        lines.append("| Name | Description | Tags | Link |")
        lines.append("|------|-------------|------|------|")

        for entry in entries:
            name = entry["name"]
            desc = entry["description"][:80] if entry["description"] else "—"
            tags = entry["tags"] if entry["tags"] else "—"
            try:
                rel_path = entry["path"].relative_to(project_root)
            except ValueError:
                rel_path = entry["path"]
            link = f"[SKILL.md]({rel_path})"
            lines.append(f"| {name} | {desc} | {tags} | {link} |")

        lines.append("")
        return "\n".join(lines)
